# Generated by Django 5.1.7 on 2025-08-04 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories_per_100g', models.PositiveIntegerField()),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sodium_per_100g', models.PositiveIntegerField(default=0, help_text='Sódio em mg')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, help_text='Preço estimado por 100g', max_digits=8)),
                ('category', models.CharField(choices=[('protein', 'Proteínas'), ('carbs', 'Carboidratos'), ('fats', 'Gorduras'), ('vegetables', 'Vegetais'), ('fruits', 'Frutas'), ('dairy', 'Laticínios'), ('grains', 'Grãos'), ('other', 'Outros')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Refeição', max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantidade em gramas', max_digits=6)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.meal')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Altura em cm', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg', max_digits=5, null=True)),
                ('objective', models.CharField(choices=[('lose', 'Perder Peso'), ('maintain', 'Manter Peso'), ('gain', 'Ganhar Peso')], default='maintain', max_length=10)),
                ('daily_calories', models.PositiveIntegerField(default=2000)),
                ('protein_goal', models.PositiveIntegerField(default=150, help_text='Proteínas em gramas')),
                ('carbs_goal', models.PositiveIntegerField(default=250, help_text='Carboidratos em gramas')),
                ('fat_goal', models.PositiveIntegerField(default=67, help_text='Gorduras em gramas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories_consumed', models.PositiveIntegerField(default=0)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('protein_consumed', models.PositiveIntegerField(default=0)),
                ('carbs_consumed', models.PositiveIntegerField(default=0)),
                ('fat_consumed', models.PositiveIntegerField(default=0)),
                ('fiber_consumed', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'food')},
            },
        ),
    ]
