# Generated by Django 5.1.7 on 2025-08-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', help_text='Gênero para cálculos metabólicos', max_length=1),
        ),
    ]
