# Generated by Django 5.1 on 2025-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil do usuário', null=True, upload_to='profile_photos/'),
        ),
    ]
