# Generated by Django 5.1.7 on 2025-09-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fiber_goal',
            field=models.PositiveIntegerField(default=30, help_text='Fibras em gramas'),
        ),
    ]
